/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kataFizzBuzzStarterJava;

public class FizzBuzz {
    public boolean someLibraryMethod() {
        return true;
    }
}
