/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kataFizzBuzzStarterJava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FizzBuzzTest {
    @Test void testSomeLibraryMethod() {
        FizzBuzz classUnderTest = new FizzBuzz();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
